spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#freemarker模板配置
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  http:
    multipart:
      max-file-size: 1
      max-request-size: -1
    activiti:
      check-process-definitions: false
  mvc:
    view:

server:
  session:
    timeout: 3600

---
#环境
spring:
  profiles: dev
  datasource:
#本地数据库
   url: jdbc:mysql://localhost:3306/fogworkflowsim?useUnicode=true&useSSL=false&amp;characterEncoding=utf8&allowMultiQueries=true
   username: root
   password: root
#isec数据库
#   url: jdbc:mysql://47.74.84.61:3306/fogworkflowsim?useUnicode=true&useSSL=false&amp;characterEncoding=utf8&allowMultiQueries=true
#   username: king
#   password: ccis@2019
#临时数据库
#   url: jdbc:mysql://47.98.222.243:3306/fogworkflowsim?useUnicode=true&useSSL=false&amp;characterEncoding=utf8&allowMultiQueries=true
#   username: root
#   password: ccis@2020
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



server:
  port: 8089

#windows文件路径选择
path:
  activitiXmlPath: E:\\activitiXML\\
  dagXmlPath: E:\\dagXML\\
  modelXmlPath: E:\\modelXML\\

#linux文件路径选择
#path:
#  activitiXmlPath: /root/sim/activitiXML/
#  dagXmlPath: /root/sim/dagXML/
#  modelXmlPath: /root/sim/modelXML/

